version: 2.1

command:
  print_pipeline_id:
    description: "A simple command that outputs the circle ci workflow ID"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "hello world" > output.txt
      - persist_to_workspace:
          root: .
          paths: 
            - output.txt

  print_output_file:
    docker: 
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run: cat output.txt
      - print_pipeline_id

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
        